// layout.tsx
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Persistent Title Bar */}
        <header className='bg-blue-600 text-white p-4'>
          <div className='container mx-auto flex justify-between items-center'>
            <h1 className='text-2xl font-bold'>My Application Title</h1>
            <nav>
              <ul className='flex space-x-4'>
                <li>
                  <a href='/' className='hover:underline'>
                    Home
                  </a>
                </li>
                <li>
                  <a href='/recipes' className='hover:underline'>
                    RecipesApp
                  </a>
                </li>
                <li>
                  <a href='/contact' className='hover:underline'>
                    Contact
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        {/* Main content */}
        <main className='container mx-auto p-4'>{children}</main>
      </body>
    </html>
  );
}